src/apps/productos/urls.py
from django.urls import path

from . import views

app_name = "productos"

urlpatterns = [
path("ListarProductos/", views.listar, name="listar")

]

src/comercio/urls.py
from django.conf                import settings
from django.contrib             import admin
from django.conf.urls.static    import static
from django.contrib.auth        import views as auth_views
from django.urls                import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Includes
    path('Productos/', include('apps.productos.urls')),

    # Url propias del Proyecto
    path('', views.inicio, name="inicio"),
    path('IniciarSesion/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/',auth_views.logout_then_login, name="logout")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/productos/models.py
from django.db import models

class Productos(models.Model):

    nombre = models.CharField(max_length=250)
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    cantidad = models.IntegerField(default=0)
    activo = models.BooleanField(default=True)
    imagen = models.ImageField(upload_to="productos", null=True)
    class Meta:
        db_table = 'productos'

    def __str__(self):
        return f"[{self.id}] {self.nombre}"

src/apps/productos/views.py
from django.shortcuts import render

from .models import Productos

def listar(request):
    template_name = "productos/listar.html"
    ctx = {
        "nombre_usuario": "Juan Manuel",
        "lista_productos": Productos.objects.all().order_by("-id")#trae todos
        #"lista_productos": Productos.objects.filter(id=2) #trae solo uno
        #"lista_productos": Productos.objects.filter(nombre="Cargador USB") #trae solo uno
        #"lista_productos": Productos.objects.filter(nombre="Cargador USB").order by("nombre","id")#first() #trae solo uno
        #"lista_productos": Productos.objects.get(id=2)
    }
    return render(request,template_name,ctx)
    '''
    Si usamos get() devuelve un elemento, en el caso de dos productos
    con el mismo nombre devolveria y daria error.
    Cuando necesitamos que devuelvan varios usamos el filter()
    '''

src/comercio/views.py
from django.shortcuts import render

from apps.productos.models import Productos

def inicio(request):
    template_name = "index.html"
    ''' para ver que me devuelve el contex en la consola hago un print
    -id significa orden descendente
    [:2] es un corte sobre la lista y le digo que me retorne los ultimos dos elementos
    '''
    ultimos_productos = Productos.objects.all().order_by('-id') [:2]
    #print(ultimos_productos)
    ctx = {
        'ultimos_productos': ultimos_productos
    }
    return render(request,template_name,ctx)
'''**** reemplazamos la vista basada en funcion por vista basada en clase 
def login(request):
    template_name = "login.html"
    ctx = {}
    return render(request,template_name,ctx)
'''

src/templates/base/base.html
{% load static %}

<html lang="en"><link type="text/css" id="dark-mode" rel="stylesheet" href=""><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Pagina de Inicio</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!--<link href="blog.css" rel="stylesheet">-->
  </head>

  <body>

    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'inicio' %}">Bienvenido a nuestro Comercio</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
            {% if user.is_authenticated %}
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Salir</a>
            {% else %}
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'login'%}">Iniciar Sesión</a>
            {% endif %}
                        
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          <a class="p-2 text-muted" href="{%url 'productos:listar' %}">Ir al catalogo</a>
          
        </nav>
      </div>

      <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
          <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
          <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
          <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
        </div>
      </div>      
    </div>

    <main role="main" class="container">
        {% block contenido %}

        {% endblock contenido %}

      

    </main><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <!-- <script src="../../assets/js/vendor/holder.min.js"></script>-->
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  

<svg xmlns="http://www.w3.org/2000/svg" width="200" height="250" viewBox="0 0 200 250" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="13" style="font-weight:bold;font-size:13pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text></svg></body></html>

src/templates/index.html
{% extends "base/base.html" %}

{% block contenido %}

    <div class="row">
	<div class="blog-main">
    <h1 style="margin: 50px;">Ultimas Novedades</h1>
		<!--<h3 class="pb-3 mb-4 font-italic border-bottom">
			Lista de Productos
		</h3>-->

		<!-- Agregar lista de productos -->
		<!--<h1>Hola {{nombre_usuario}}</h1>-->

		<div class="row mb-2">
			{% for p in ultimos_productos %}
				<div class="col-md-6">
					  {% include "productos/includes/bloque_producto.html" %}
				</div>
			{% empty %}
				<li>No existen productos</li>
			{% endfor %}
		</div>

	</div><!-- /.blog-main -->
</div>
{% endblock contenido %}

src/templates/login.html
{% load static%}
    
<html lang="en"><link type="text/css" id="dark-mode" rel="stylesheet" href=""><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Iniciar Sesión</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
  </head>

<body class="text-center">
    <form class="form-signin" method="POST"> {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Iniciar Sesión</h1>

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <strong>{{field}}:</strong> {{error}}
                    </div>
                {% endfor %}
            {% endfor %}
                
            {% for error in  form.non_field_errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{error}}
                </div>
            {% endfor %}


        {% endif %}

        <label for="username" class="sr-only">Nombre de Usuario</label>
        <input type="text" id="username" class="form-control" name="username" placeholder="Ingrese nombre de usuario"
            required="" autofocus="">
        <label for="inputPassword" class="sr-only">Contraseña</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Ingrese contraseña" required="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Iniciar Sesión</button>
        <p class="mt-5 mb-3 text-muted"><a href="{% url 'inicio' %}">Volver al inicio</a></p>
    </form>


</body>
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="250" viewBox="0 0 200 250" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="13" style="font-weight:bold;font-size:13pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text></svg></body></html>

src/templates/productos/includes/bloque_producto.html
<div class="card flex-md-row mb-4 box-shadow h-md-250">
						<div class="card-body d-flex flex-column align-items-start">
							<strong class="d-inline-block mb-2 text-primary">Tecnologia</strong>
							<h3 class="mb-0">
								<a class="text-dark" href="#">{{p.nombre}}</a>
							</h3>
							<p class="card-text mb-auto">$ {{p.precio}}</p>
							<a href="#">Ver mas</a>
						</div>
                        {% if p.imagen %}
                            <img class="card-img-right flex-auto d-none d-md-block" src="{{p.imagen.url}}" data-holder-rendered="true">
                        {% else %}
                            <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
							alt="Thumbnail [200x250]" style="width: 200px; height: 250px;"
							src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17d78dd6e53%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17d78dd6e53%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.1953125%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
							data-holder-rendered="true">
                        {% endif %}
					</div>

src/templates/productos/listar.html
{% extends "base/base.html" %} 

{% block contenido %}
<div class="row">
	<div class="blog-main">
		<!--<h3 class="pb-3 mb-4 font-italic border-bottom">
			Lista de Productos
		</h3>-->

		<!-- Agregar lista de productos -->
		<!--<h1>Hola {{nombre_usuario}}</h1>-->

		<div class="row mb-2">
			{% for p in lista_productos %}
				<div class="col-md-6">
					{% include "productos/includes/bloque_producto.html" %}
				</div>
			{% empty %}
				<li>No existen productos</li>
			{% endfor %}
		</div>

	</div><!-- /.blog-main -->
</div>
{% endblock contenido %}